import type { RankInfo, Course } from '../types/game.ts'

export const COURSES: Course[] = [
  {
    id: 'beginner',
    name: '初級SESコース',
    description: '短い単語でウォーミングアップ',
    timeLimit: 30000,
    baseTimeBonus: 1000,
    monthsPerWord: 2,
    wordTimerMultiplier: 1.5,
    words: [
      { word: '単価', kana: 'たんか', flavor: 'あなたの値段がついた瞬間' },
      { word: '現場', kana: 'げんば', flavor: '第二の故郷' },
      { word: '案件', kana: 'あんけん', flavor: 'ガチャの中身' },
      { word: '名刺', kana: 'めいし', flavor: 'お客様先のロゴが入っている' },
      { word: '入社', kana: 'にゅうしゃ', flavor: '夢と希望の第一歩' },
      { word: '研修', kana: 'けんしゅう', flavor: '3日で終わる座学' },
      { word: '常駐', kana: 'じょうちゅう', flavor: '自社より長くいる場所' },
      { word: '帰社日', kana: 'きしゃび', flavor: '月1回だけ思い出す自社の存在' },
      { word: '待機', kana: 'たいき', flavor: '仕事がない。でも給料は（少し）出る' },
      { word: '面談', kana: 'めんだん', flavor: 'スキルシートの内容を暗記する時間' },
      { word: '退職', kana: 'たいしょく', flavor: '沼からの脱出方法' },
      { word: '勤怠', kana: 'きんたい', flavor: '二重管理が基本' },
      { word: '設計', kana: 'せっけい', flavor: 'エクセルで書くもの' },
      { word: '進捗', kana: 'しんちょく', flavor: '順調です（嘘ではない）' },
      { word: '納期', kana: 'のうき', flavor: '絶対に守るもの（らしい）' },
      { word: '単体', kana: 'たんたい', flavor: 'テストの名を借りた動作確認' },
      { word: '本番', kana: 'ほんばん', flavor: 'ここでバグが見つかる' },
      { word: '見積もり', kana: 'みつもり', flavor: '3倍にしても足りない' },
      { word: '派遣', kana: 'はけん', flavor: 'SESとは違います（建前）' },
      { word: '委託', kana: 'いたく', flavor: '便利な言い回し' },
      { word: '手戻り', kana: 'てもどり', flavor: '仕様変更のたびに発生する' },
      { word: '端末', kana: 'たんまつ', flavor: '支給されるまで一週間かかる' },
      { word: '打合せ', kana: 'うちあわせ', flavor: '一日の半分を占める' },
      { word: '炎上', kana: 'えんじょう', flavor: '参画した初日から' },
      { word: '残業', kana: 'ざんぎょう', flavor: '自主的なものです' },
      { word: '客先', kana: 'きゃくさき', flavor: '実質的な自社' },
      { word: '配属', kana: 'はいぞく', flavor: 'ガチャの結果発表' },
      { word: '着任', kana: 'ちゃくにん', flavor: '現場の空気を読む初日' },
      { word: '参画', kana: 'さんかく', flavor: '入場とも言う' },
      { word: '離脱', kana: 'りだつ', flavor: '退場とも言う' },
      { word: '権限', kana: 'けんげん', flavor: '足りないのが常' },
      { word: '稼働', kana: 'かどう', flavor: '月の時間で管理される' },
      { word: '顔合わせ', kana: 'かおあわせ', flavor: '面談ではありません' },
      { word: '入館証', kana: 'にゅうかんしょう', flavor: '絶対に失くさないで' },
      { word: '後任', kana: 'こうにん', flavor: '前任者のことは知らない' },
      { word: '自社', kana: 'じしゃ', flavor: 'もう二度と戻れない場所のこと' },
      { word: '監視', kana: 'かんし', flavor: 'ガチャのハズレ' },
      { word: '夜勤', kana: 'やきん', flavor: '日勤もあるんだよ' },
      { word: '営業', kana: 'えいぎょう', flavor: '稀に現場に来る人のこと' },
      { word: '契約', kana: 'けいやく', flavor: '3ヶ月更新が基本' },
      { word: '保守', kana: 'ほしゅ', flavor: '誰もやりたがらない' },
      { word: '報告', kana: 'ほうこく', flavor: '問題ありません（ある）' },
      { word: '撤退', kana: 'てったい', flavor: '炎上案件からの生還' },
      { word: '延長', kana: 'えんちょう', flavor: '嬉しいような悲しいような' },
      { word: '外注', kana: 'がいちゅう', flavor: '外注の外注の外注' },
      { word: '仕様', kana: 'しよう', flavor: 'バグじゃなくて仕様です' },
      { word: '転職', kana: 'てんしょく', flavor: '心の中でいつも考えている' },
      { word: '増員', kana: 'ぞういん', flavor: '人が足りない時の魔法の言葉' },
      { word: '結合', kana: 'けつごう', flavor: 'テストの名を借りた戦場' },
      { word: '出向', kana: 'しゅっこう', flavor: '派遣じゃないです（建前）' },
      { word: '要件', kana: 'ようけん', flavor: '毎回変わるもの' },
      { word: '工程', kana: 'こうてい', flavor: '遅れているのが通常運転' },
      { word: '検証', kana: 'けんしょう', flavor: 'エビデンスを残せと言われる' },
      { word: '障害', kana: 'しょうがい', flavor: '金曜の夕方に起きる' },
      { word: '承認', kana: 'しょうにん', flavor: '上長が捕まらない' },
      { word: '予算', kana: 'よさん', flavor: 'いつも足りない' },
      { word: '引越し', kana: 'ひっこし', flavor: '通勤時間を減らすために' },
      { word: '座席', kana: 'ざせき', flavor: '自分の席がない日もある' },
      { word: '休憩', kana: 'きゅうけい', flavor: 'タバコ部屋が情報交換の場' },
      { word: '日報', kana: 'にっぽう', flavor: '書くことが思いつかない' },
      { word: '経費', kana: 'けいひ', flavor: '交通費は出るけど上限あり' },
      { word: '書類', kana: 'しょるい', flavor: '紙文化が根強い' },
      { word: '朝会', kana: 'あさかい', flavor: '毎朝15分のルーティン' },
      { word: '検収', kana: 'けんしゅう', flavor: 'OKが出るまで安心できない' },
      { word: '体調', kana: 'たいちょう', flavor: '崩しても休めない空気' },
      { word: '昼食', kana: 'ちゅうしょく', flavor: '毎日コンビニ弁当' },
      { word: '通勤', kana: 'つうきん', flavor: '片道1時間半は当たり前' },
      { word: '評価', kana: 'ひょうか', flavor: '見えない基準で決まる' },
      { word: '申請', kana: 'しんせい', flavor: 'ハンコが5つ必要' },
      { word: '指示', kana: 'しじ', flavor: '曖昧なことが多い' },
    ],
  },
  {
    id: 'intermediate',
    name: '中級SESコース',
    description: 'IT・SES複合語を打ちまくれ',
    timeLimit: 40000,
    baseTimeBonus: 2000,
    monthsPerWord: 3,
    wordTimerMultiplier: 1.0,
    words: [
      { word: '客先常駐', kana: 'きゃくさきじょうちゅう', flavor: 'ここが第二の故郷になる' },
      { word: 'バージョン管理', kana: 'ばーじょんかんり', flavor: '使ってないプロジェクトもある' },
      { word: '準委任契約', kana: 'じゅんいにんけいやく', flavor: '指揮命令は自社のはず…のはず' },
      { word: 'スキルシート', kana: 'すきるしーと', flavor: '書いたことない技術もとりあえず記載' },
      { word: 'レガシーコード', kana: 'れがしーこーど', flavor: '書いた人はもういない' },
      { word: '多重下請け', kana: 'たじゅうしたうけ', flavor: '上流が誰なのかわからない' },
      { word: '人月単価', kana: 'にんげつたんか', flavor: '見積もりの基本単位' },
      { word: '経歴詐称', kana: 'けいれきさしょう', flavor: 'Java歴3年（実質3ヶ月）' },
      { word: '設計書更新', kana: 'せっけいしょこうしん', flavor: 'コードの後に書く本末転倒' },
      { word: 'エビデンス', kana: 'えびでんす', flavor: 'スクショを撮る仕事' },
      { word: 'コードレビュー', kana: 'こーどれびゅー', flavor: '指摘が多すぎて心が折れる' },
      { word: 'デッドライン', kana: 'でっどらいん', flavor: '死線を何度も越えてきた' },
      { word: '単体テスト', kana: 'たんたいてすと', flavor: '書く時間がないと言われる' },
      { word: 'ソースコード', kana: 'そーすこーど', flavor: '読めるかどうかは別の話' },
      { word: 'テストケース', kana: 'てすとけーす', flavor: '手動で全件実施' },
      { word: 'リモートワーク', kana: 'りもーとわーく', flavor: 'セキュリティ上の理由で不可' },
      { word: '勤怠管理', kana: 'きんたいかんり', flavor: '二つのシステムに入力する' },
      { word: '仕様変更', kana: 'しようへんこう', flavor: '昨日と今日で仕様が違う' },
      { word: '瑕疵対応', kana: 'かしたいおう', flavor: '無限に湧くバグとの戦い' },
      { word: '定時退社', kana: 'ていじたいしゃ', flavor: '周りが帰らないと帰れない' },
      { word: 'ブラック案件', kana: 'ぶらっくあんけん', flavor: '入ってみるまでわからない' },
      { word: 'スキルアップ', kana: 'すきるあっぷ', flavor: '現場では学べないと気づいた' },
      { word: 'プロパー社員', kana: 'ぷろぱーしゃいん', flavor: '同じ仕事でも待遇が違う' },
      { word: 'サービス残業', kana: 'さーびすざんぎょう', flavor: '自主的にやっています' },
      { word: 'エクセル方眼紙', kana: 'えくせるほうがんし', flavor: '設計書はExcelで書く文化' },
      { word: '客先面談', kana: 'きゃくさきめんだん', flavor: '笑顔の練習をしてから行く' },
      { word: '秘密保持契約', kana: 'ひみつほじけいやく', flavor: '何も話せなくなる魔法の紙' },
      { word: '進捗報告会', kana: 'しんちょくほうこくかい', flavor: '毎朝15分のはずが1時間' },
      { word: '偽装請負', kana: 'ぎそううけおい', flavor: 'これは準委任です（震え声）' },
      { word: '工数見積もり', kana: 'こうすうみつもり', flavor: '3倍にしても足りないという不思議' },
      { word: '再委託禁止', kana: 'さいいたくきんし', flavor: '守られているか誰も確認しない' },
      { word: 'プロジェクト管理', kana: 'ぷろじぇくとかんり', flavor: 'エクセルで管理するスタイル' },
      { word: '人事考課', kana: 'じんじこうか', flavor: '基本的に全て自己申告です' },
      { word: 'ビジネスパートナー', kana: 'びじねすぱーとなー', flavor: 'ビジネス上の対等な…対等な関係です！' },
      { word: 'デスマーチ', kana: 'ですまーち', flavor: '全員の目が死んでいる' },
      { word: '環境構築', kana: 'かんきょうこうちく', flavor: '手順書通りにやっても動かない' },
      { word: '要件定義', kana: 'ようけんていぎ', flavor: '終わったはずなのに追加される' },
      { word: '技術面談', kana: 'ぎじゅつめんだん', flavor: '圧迫面接とも言う' },
      { word: 'ドキュメント', kana: 'どきゅめんと', flavor: '誰も読まないけど必要' },
      { word: 'オンプレミス', kana: 'おんぷれみす', flavor: 'クラウドは許可されない' },
      { word: 'バッチ処理', kana: 'ばっちしょり', flavor: '夜中に動いて朝にコケる' },
      { word: 'ヘルプデスク', kana: 'へるぷですく', flavor: 'パスワード忘れの対応係' },
      { word: '結合テスト', kana: 'けつごうてすと', flavor: '全部つなげたら全部壊れた' },
      { word: 'マイルストーン', kana: 'まいるすとーん', flavor: '一度も守られたことがない' },
      { word: '業務委託', kana: 'ぎょうむいたく', flavor: '実態は派遣と変わらない' },
      { word: '参画期間', kana: 'さんかくきかん', flavor: '延長のたびに魂が削れる' },
      { word: 'インフラ構築', kana: 'いんふらこうちく', flavor: '設計書はあるけど古い' },
      { word: '本番リリース', kana: 'ほんばんりりーす', flavor: '金曜の夜にやるな' },
      { word: 'ウォーターフォール', kana: 'うぉーたーふぉーる', flavor: '手戻りできないのに手戻りする' },
      { word: 'コンプライアンス', kana: 'こんぷらいあんす', flavor: '研修は毎年受けるけど現場は…' },
      { word: 'パワポ資料', kana: 'ぱわぽしりょう', flavor: '中身より見た目を求められる' },
      { word: '稼働率管理', kana: 'かどうりつかんり', flavor: '100%を超えても誰も驚かない' },
      { word: 'セキュリティ研修', kana: 'せきゅりてぃけんしゅう', flavor: '毎年同じ内容' },
      { word: '運用保守', kana: 'うんようほしゅ', flavor: '終わりのない旅' },
      { word: '負荷テスト', kana: 'ふかてすと', flavor: '本番で落ちてから気づく' },
      { word: '技術負債', kana: 'ぎじゅつふさい', flavor: '返済計画はない' },
      { word: 'コミットログ', kana: 'こみっとろぐ', flavor: '「修正」としか書いてない' },
      { word: 'アジャイル開発', kana: 'あじゃいるかいはつ', flavor: 'スプリントの名を借りた残業' },
      { word: '情報漏洩', kana: 'じょうほうろうえい', flavor: '一番怖いインシデント' },
      { word: 'リファクタリング', kana: 'りふぁくたりんぐ', flavor: '今はその時じゃないと言われ続ける' },
      { word: 'ペアプログラミング', kana: 'ぺあぷろぐらみんぐ', flavor: '隣で見られるプレッシャー' },
      { word: 'クラウド移行', kana: 'くらうどいこう', flavor: '予算が3倍になった' },
      { word: 'システム移行', kana: 'しすてむいこう', flavor: '旧システムが動いている限り終わらない' },
      { word: 'データ移行', kana: 'でーたいこう', flavor: '文字化けとの戦い' },
      { word: 'キャパシティ管理', kana: 'きゃぱしてぃかんり', flavor: '人もサーバーも足りない' },
      { word: 'バックアップ', kana: 'ばっくあっぷ', flavor: '取ってなかった時の絶望' },
      { word: 'ステージング環境', kana: 'すてーじんぐかんきょう', flavor: '本番と微妙に違う' },
    ],
  },
  {
    id: 'advanced',
    name: '上級SESコース',
    description: 'ことわざ×IT/SESあるあるで限界に挑め',
    timeLimit: 50000,
    baseTimeBonus: 3000,
    monthsPerWord: 4,
    wordTimerMultiplier: 0.7,
    words: [
      // ── IT/SESあるある × ことわざ・慣用句 ──
      { word: '監視の上にも三年', kana: 'かんしのうえにもさんねん', flavor: '10年監視やっている先輩を見て戦慄' },
      { word: 'ベテランもサーバーを落とす', kana: 'べてらんもさーばーをおとす', flavor: '猿も木から落ちる' },
      { word: '七デプロイ八ロールバック', kana: 'ななでぷろいはちろーるばっく', flavor: '七転び八起きとは言うけれど' },
      { word: '急がばテスト', kana: 'いそがばてすと', flavor: '急いでリリースした結果がこれ' },
      { word: '二案件追う者は一案件も納品できず', kana: 'にあんけんおうものはいちあんけんものうひんできず', flavor: '掛け持ちの末路' },
      { word: '障害対応中にもう一件障害', kana: 'しょうがいたいおうちゅうにもういっけんしょうがい', flavor: '泣きっ面に蜂とはこのこと' },
      { word: '棚からリモート案件', kana: 'たなからりもーとあんけん', flavor: '棚からぼたもち' },
      { word: 'ベテランも本番で誤DELETE', kana: 'べてらんもほんばんでごDELETE', flavor: '弘法も筆の誤り' },
      { word: 'ログは出てたのに誰も見てない', kana: 'ろぐはでてたのにだれもみてない', flavor: '灯台下暗しの極み' },
      { word: '三社寄れば責任のなすりつけ', kana: 'さんしゃよればせきにんのなすりつけ', flavor: '文殊の知恵は出てこない' },
      { word: '技術より単価', kana: 'ぎじゅつよりたんか', flavor: '花より団子' },
      { word: 'できるエンジニアはスキルシートを盛らない', kana: 'できるえんじにあはすきるしーとをもらない', flavor: '営業は勝手に盛る' },
      { word: '顧客の耳にリスク報告', kana: 'こきゃくのみみにりすくほうこく', flavor: '右から左に聞き流される' },
      { word: '百行の設計書より一枚のスクショ', kana: 'ひゃくぎょうのせっけいしょよりいちまいのすくしょ', flavor: '百聞は一見にしかず' },
      { word: 'リリースは寝ずに見守れ', kana: 'りりーすはねずにみまもれ', flavor: '果報は寝て待てとは真逆の世界' },
      { word: '障害起きぬ先の冗長化', kana: 'しょうがいおきぬさきのじょうちょうか', flavor: '転ばぬ先の杖だが予算がない' },
      { word: 'DELETEしたデータは戻らない', kana: 'DELETEしたでーたはもどらない', flavor: '覆水盆に返らず。WHERE句を忘れるな' },
      { word: '現場の中のエンジニア市場を知らず', kana: 'げんばのなかのえんじにあしじょうをしらず', flavor: '井の中の蛙だった' },
      { word: '一ヶ月先は別現場', kana: 'いっかげつさきはべつげんば', flavor: '一寸先は闇SES' },
      { word: '障害起きてドキュメント整う', kana: 'しょうがいおきてどきゅめんとととのう', flavor: '雨降って地固まる' },
      { word: '定時で帰る杭は打たれる', kana: 'ていじでかえるくいはうたれる', flavor: '出る杭は打たれるを体現' },
      { word: 'サーバーはインフラ屋に聞け', kana: 'さーばーはいんふらやにきけ', flavor: '餅は餅屋' },
      { word: '技術的負債も積もれば炎上となる', kana: 'ぎじゅつてきふさいもつもればえんじょうとなる', flavor: '塵も積もれば山となる' },
      { word: '稼働は単価なり', kana: 'かどうはたんかなり', flavor: '時は金なり' },
      { word: '一障害二徹夜', kana: 'いちしょうがいにてつや', flavor: '一石二鳥の真逆をいく' },
      { word: 'バックアップあれば憂いなし', kana: 'ばっくあっぷあればうれいなし', flavor: '備えあれば憂いなし。ないと地獄' },
      { word: '障害が起きればエンジニアが増える', kana: 'しょうがいがおきればえんじにあがふえる', flavor: '風が吹けば桶屋が儲かる的な' },
      { word: '受注前に要員をアサインする', kana: 'じゅちゅうまえによういんをあさいんする', flavor: '捕らぬ狸の皮算用' },
      { word: '炎上案件に入らずんば経験を得ず', kana: 'えんじょうあんけんにはいらずんばけいけんをえず', flavor: '虎穴に入らずんば虎子を得ず' },
      { word: '設計するよりコード書くが早し', kana: 'せっけいするよりこーどかくがはやし', flavor: '案ずるより産むが易し' },
      { word: '聞くは一時の恥聞かぬは一生の障害', kana: 'きくはいっときのはじきかぬはいっしょうのしょうがい', flavor: '仕様を確認しなかった結果がこれ' },
      { word: '納品よければ全てよし', kana: 'のうひんよければすべてよし', flavor: '途中の修羅場は忘れよう' },
      { word: '知らぬが商流', kana: 'しらぬがしょうりゅう', flavor: '何次請けかは知らない方が幸せ' },
      { word: '立つエンジニア跡を濁さず', kana: 'たつえんじにああとをにごさず', flavor: '引き継ぎ書は置いていけ' },
      { word: '営業の顔も三度まで', kana: 'えいぎょうのかおもさんどまで', flavor: '同じ案件を三回断ると態度が豹変' },
      { word: '石橋を叩いてからデプロイ', kana: 'いしばしをたたいてからでぷろい', flavor: '本番ぶっつけは二度としない' },
      { word: '隣のエンジニアは青く見える', kana: 'となりのえんじにあはあおくみえる', flavor: '隣の芝生は青い' },
      { word: '現場に入っては現場に従え', kana: 'げんばにいってはげんばにしたがえ', flavor: '郷に入っては郷に従え。Git運用が全部違う' },
      { word: '待機していれば案件が来る', kana: 'たいきしていればあんけんがくる', flavor: '待てば海路の日和ありを信じて' },
      { word: '三十六計逃げるが転職', kana: 'さんじゅうろっけいにげるがてんしょく', flavor: '逃げるが勝ち' },
      { word: '炎上案件に一人追加', kana: 'えんじょうあんけんにひとりついか', flavor: '焼け石に水' },
      { word: '納期に品質はかえられぬ', kana: 'のうきにひんしつはかえられぬ', flavor: '背に腹はかえられぬ' },
      { word: 'リモートから障害対応', kana: 'りもーとからしょうがいたいおう', flavor: '二階から目薬' },
      { word: 'エンジニアにroot権限', kana: 'えんじにあにrootけんげん', flavor: '鬼に金棒だが事故も起きる' },
      { word: '顧客にシステム構成図', kana: 'こきゃくにしすてむこうせいず', flavor: '猫に小判' },
      { word: 'エンジニアにもスーツ', kana: 'えんじにあにもすーつ', flavor: '馬子にも衣装。面談の日だけ' },
      { word: '三日でリファクタリング断念', kana: 'みっかでりふぁくたりんぐだんねん', flavor: '三日坊主' },
      { word: 'バグ修正から新機能が生まれる', kana: 'ばぐしゅうせいからしんきのうがうまれる', flavor: '瓢箪から駒' },
      { word: 'コードを見て設計を見ず', kana: 'こーどをみてせっけいをみず', flavor: '木を見て森を見ず' },
      { word: 'システム作ってテスト書かず', kana: 'しすてむつくっててすとかかず', flavor: '仏作って魂入れず' },
      { word: 'レビュー指摘に糠に釘', kana: 'れびゅーしてきにぬかにくぎ', flavor: '同じ指摘を三回目' },
      { word: '議論よりログ', kana: 'ぎろんよりろぐ', flavor: '論より証拠' },
      { word: '新人の手も借りたい', kana: 'しんじんのてもかりたい', flavor: '猫の手も借りたいほど忙しい' },
      { word: '技術的負債の返済時', kana: 'ぎじゅつてきふさいのへんさいどき', flavor: '年貢の納め時' },
      { word: '大手ベンダーには巻かれろ', kana: 'おおてべんだーにはまかれろ', flavor: '長いものには巻かれろ' },
      { word: '実装してドキュメントを欠く', kana: 'じっそうしてどきゅめんとをかく', flavor: '画竜点睛を欠く' },
      { word: 'セキュリティ屋のパスワードが弱い', kana: 'せきゅりてぃやのぱすわーどがよわい', flavor: '紺屋の白袴' },
      { word: '隣のチームの炎上は対岸の火事', kana: 'となりのちーむのえんじょうはたいがんのかじ', flavor: '明日は我が身なのに' },
      { word: 'ログはコードほどに物を言う', kana: 'ろぐはこーどほどにものをいう', flavor: '目は口ほどに物を言う' },
      { word: '監視三年運用八年', kana: 'かんしさんねんうんようはちねん', flavor: 'いつ上流工程に行けますか' },
      { word: '名刺を切らしておりまして', kana: 'めいしをきらしておりまして', flavor: '自社の名刺はあります' },
      { word: '大いなる力には大いなる責任が伴う', kana: 'おおいなるちからにはおおいいなるせきにんがともなう', flavor: '一度は必ず見るやつ' },
    ],
  },
]

export const BONUS_WORDS: import('../types/game.ts').Word[] = [
  // ── 危険コマンド系 ──
  { word: 'rm -rf /*', kana: 'あーるえむはいふんあーるえふすらっしゅあすたりすく', flavor: '全てを消し去る禁断のコマンド' },
  { word: 'sudo su -', kana: 'すーどぅーえすゆーはいふん', flavor: '神になる呪文' },
  { word: 'chmod 777', kana: 'しーえいちもっどなななななな', flavor: 'セキュリティ？知らない子ですね' },
  { word: 'kill -9', kana: 'きるはいふんないん', flavor: '問答無用の強制終了' },
  { word: 'dd if=/dev/zero', kana: 'でぃーでぃーいふいこーるでぶぜろ', flavor: 'ディスクを虚無で埋め尽くす' },
  { word: 'fork bomb', kana: 'ふぉーくぼむ', flavor: ':(){ :|:& };: 見た目も爆弾' },
  { word: 'git push --force', kana: 'ぎっとぷっしゅふぉーす', flavor: '歴史改変の禁術' },
  { word: 'DROP TABLE users', kana: 'どろっぷてーぶるゆーざーず', flavor: 'ユーザーが全員消えた日' },
  { word: 'eval(input())', kana: 'いーばるいんぷっと', flavor: '任意コード実行の入り口' },
  { word: 'SELECT * FROM', kana: 'せれくとあすたりすくふろむ', flavor: '本番DBで全件取得する勇気' },
  { word: 'cat /etc/passwd', kana: 'きゃっとえとせとらぱすわーど', flavor: 'まず最初に見るファイル' },
  { word: 'git reset --hard', kana: 'ぎっとりせっとはーど', flavor: 'コミット履歴ごと消し飛ぶ' },
  { word: 'truncate table', kana: 'とらんけーとてーぶる', flavor: 'WHERE句なしの恐怖' },
  { word: 'shutdown -h now', kana: 'しゃっとだうんえいちなう', flavor: '本番サーバーで打ったら終わり' },
  { word: 'curl | bash', kana: 'かーるぱいぷばっしゅ', flavor: '中身を見ずに実行する勇気' },
  { word: 'mkfs /dev/sda', kana: 'えむけーえふえすでぶえすでぃーえー', flavor: 'フォーマットしますか？はい' },
  { word: 'iptables -F', kana: 'あいぴーてーぶるずふらっしゅ', flavor: 'ファイアウォールが全開放' },
  { word: 'git stash drop', kana: 'ぎっとすたっしゅどろっぷ', flavor: '退避した変更が闇に消える' },
  { word: 'DELETE FROM users', kana: 'でりーとふろむゆーざーず', flavor: 'WHERE忘れて全件削除' },
  { word: 'format c:', kana: 'ふぉーまっとしーころん', flavor: 'Windowsの初期化呪文' },
  // ── 開発ツール・コマンド系 ──
  { word: 'console.log', kana: 'こんそーるろぐ', flavor: 'デバッガーより信頼されている' },
  { word: 'npm install', kana: 'えぬぴーえむいんすとーる', flavor: 'node_modulesがブラックホールになる' },
  { word: 'pip install', kana: 'ぴっぷいんすとーる', flavor: '依存関係の沼へようこそ' },
  { word: 'kubectl delete pod', kana: 'きゅーぶしーてぃーえるでりーとぽっど', flavor: 'コンテナごと葬り去る' },
  { word: 'localhost:3000', kana: 'ろーかるほすとさんぜろぜろぜろ', flavor: '開発者の聖地' },
  { word: 'docker compose up', kana: 'どっかーこんぽーずあっぷ', flavor: 'コンテナが立ち上がる魔法' },
  { word: 'git cherry-pick', kana: 'ぎっとちぇりーぴっく', flavor: 'つまみ食いマージ' },
  { word: 'terraform destroy', kana: 'てらふぉーむですとろい', flavor: 'インフラが全滅する' },
  { word: 'npm audit fix', kana: 'えぬぴーえむおーでぃっとふぃっくす', flavor: '脆弱性を見なかったことにする' },
  { word: 'yarn add --dev', kana: 'やーんあどでぶ', flavor: '開発依存が増殖していく' },
  { word: 'redis-cli flushall', kana: 'れでぃすしーえるあいふらっしゅおーる', flavor: 'キャッシュが全部消えた' },
  { word: 'brew upgrade', kana: 'ぶりゅーあっぷぐれーど', flavor: '全部更新して環境が壊れる' },
  { word: 'crontab -r', kana: 'くろんたぶはいふんあーる', flavor: '定期実行が全部消える' },
  { word: 'vim :wq!', kana: 'びむころんだぶりゅーきゅーびっくりまーく', flavor: '脱出できた者だけが生き残る' },
]

export const BONUS_MULTIPLIER = 7.0
export const BONUS_WORD_COUNT = 3
export const BONUS_TIME_LIMIT = 15000 // ボーナスタイム全体の制限時間 (ms)

// ── ボーナスモード選択 ──
export const BONUS_MODE_WEIGHTS: { mode: import('../types/game.ts').BonusMode; weight: number }[] = [
  { mode: 'normal', weight: 50 },
  { mode: 'incident', weight: 30 },
  { mode: 'gacha', weight: 20 },
]

// ── SES揃い（スーパーボーナス）──
export const SUPER_BONUS_TRIGGER_WORD = 'rm -rf /*'
export const SUPER_BONUS_CHANCE = 1.0
export const SUPER_BONUS_TYPE_WORDS = ['System', 'Engineering', 'Service'] as const

// ── 障害対応モード ──
export const INCIDENTS: import('../types/game.ts').IncidentData[] = [
  {
    name: 'DBコネクション枯渇',
    description: '本番DBのコネクションプールが枯渇しています',
    commands: [
      { word: 'show processlist', kana: 'show processlist', flavor: '接続状況を確認' },
      { word: 'kill idle connections', kana: 'kill idle connections', flavor: 'アイドル接続を切断' },
      { word: 'systemctl restart mysql', kana: 'systemctl restart mysql', flavor: 'DBを再起動' },
    ],
  },
  {
    name: 'メモリリーク検知',
    description: 'アプリサーバーのメモリ使用量が95%に達しています',
    commands: [
      { word: 'top -o %MEM', kana: 'top -o %MEM', flavor: 'メモリ使用量を確認' },
      { word: 'kill -15 app', kana: 'kill -15 app', flavor: 'アプリをグレースフルに停止' },
      { word: 'systemctl restart app', kana: 'systemctl restart app', flavor: 'アプリを再起動' },
      { word: 'tail -f /var/log/app.log', kana: 'tail -f /var/log/app.log', flavor: 'ログを監視' },
    ],
  },
  {
    name: 'ディスク容量逼迫',
    description: '/dev/sda1 の使用率が98%に到達しました',
    commands: [
      { word: 'df -h', kana: 'df -h', flavor: 'ディスク使用状況を確認' },
      { word: 'du -sh /var/log/*', kana: 'du -sh /var/log/*', flavor: '犯人を探す' },
      { word: 'rm -f /var/log/*.old', kana: 'rm -f /var/log/*.old', flavor: '古いログを削除' },
    ],
  },
  {
    name: 'SSL証明書期限切れ',
    description: '本番サイトのSSL証明書が期限切れです',
    commands: [
      { word: 'openssl x509 -enddate', kana: 'openssl x509 -enddate', flavor: '期限を確認' },
      { word: 'certbot renew', kana: 'certbot renew', flavor: '証明書を更新' },
      { word: 'nginx -s reload', kana: 'nginx -s reload', flavor: 'Nginxをリロード' },
    ],
  },
  {
    name: 'DDoS攻撃検知',
    description: '異常なトラフィック増加を検知しました',
    commands: [
      { word: 'netstat -an | wc -l', kana: 'netstat -an | wc -l', flavor: '接続数を確認' },
      { word: 'iptables -A INPUT -s attacker -j DROP', kana: 'iptables -A INPUT -s attacker -j DROP', flavor: '攻撃元をブロック' },
      { word: 'systemctl restart nginx', kana: 'systemctl restart nginx', flavor: 'Webサーバー再起動' },
    ],
  },
  {
    name: 'デプロイ失敗',
    description: '本番デプロイがロールバックされました',
    commands: [
      { word: 'git log --oneline -5', kana: 'git log --oneline -5', flavor: '直近のコミットを確認' },
      { word: 'git revert HEAD', kana: 'git revert HEAD', flavor: '問題のコミットを戻す' },
      { word: 'docker compose up -d', kana: 'docker compose up -d', flavor: '再デプロイ' },
      { word: 'curl -I https://production', kana: 'curl -I https://production', flavor: '動作確認' },
    ],
  },
  {
    name: 'Redis障害',
    description: 'キャッシュサーバーが応答しません',
    commands: [
      { word: 'redis-cli ping', kana: 'redis-cli ping', flavor: '生死確認' },
      { word: 'systemctl restart redis', kana: 'systemctl restart redis', flavor: 'Redis再起動' },
      { word: 'redis-cli info memory', kana: 'redis-cli info memory', flavor: 'メモリ状況確認' },
    ],
  },
  {
    name: 'Cron暴走',
    description: 'バッチ処理が無限ループしています',
    commands: [
      { word: 'ps aux | grep cron', kana: 'ps aux | grep cron', flavor: 'プロセスを特定' },
      { word: 'kill -9 batch_pid', kana: 'kill -9 batch_pid', flavor: '強制停止' },
      { word: 'crontab -e', kana: 'crontab -e', flavor: 'スケジュール修正' },
      { word: 'tail -100 /var/log/cron.log', kana: 'tail -100 /var/log/cron.log', flavor: 'ログ確認' },
    ],
  },
  {
    name: 'DNS障害',
    description: '名前解決に失敗し全サービスがダウンしています',
    commands: [
      { word: 'dig example.com', kana: 'dig example.com', flavor: 'DNS問い合わせ' },
      { word: 'cat /etc/resolv.conf', kana: 'cat /etc/resolv.conf', flavor: 'DNSサーバー確認' },
      { word: 'systemctl restart named', kana: 'systemctl restart named', flavor: 'DNS再起動' },
    ],
  },
  {
    name: 'ログ肥大化',
    description: 'アプリログが100GBを超えてディスクを圧迫しています',
    commands: [
      { word: 'ls -lh /var/log/app/', kana: 'ls -lh /var/log/app/', flavor: 'サイズ確認' },
      { word: 'logrotate -f /etc/logrotate.conf', kana: 'logrotate -f /etc/logrotate.conf', flavor: 'ログローテーション実行' },
      { word: 'gzip /var/log/app/old.log', kana: 'gzip /var/log/app/old.log', flavor: '古いログを圧縮' },
      { word: 'df -h', kana: 'df -h', flavor: '空き容量確認' },
    ],
  },
  {
    name: 'APIレスポンス遅延',
    description: 'APIのレスポンスタイムが10秒を超えています',
    commands: [
      { word: 'curl -o /dev/null -w "%{time_total}" api', kana: 'curl -o /dev/null -w "%{time_total}" api', flavor: 'レスポンスタイム計測' },
      { word: 'mysql -e "SHOW PROCESSLIST"', kana: 'mysql -e "SHOW PROCESSLIST"', flavor: 'スロークエリ調査' },
      { word: 'redis-cli slowlog get 10', kana: 'redis-cli slowlog get 10', flavor: 'Redisスローログ' },
      { word: 'kill -HUP nginx_pid', kana: 'kill -HUP nginx_pid', flavor: 'Nginxグレースフルリロード' },
    ],
  },
  {
    name: 'Docker障害',
    description: 'コンテナが全てExitedステータスになっています',
    commands: [
      { word: 'docker ps -a', kana: 'docker ps -a', flavor: 'コンテナ状態確認' },
      { word: 'docker logs --tail 50 app', kana: 'docker logs --tail 50 app', flavor: 'ログ確認' },
      { word: 'docker compose down', kana: 'docker compose down', flavor: '全コンテナ停止' },
      { word: 'docker compose up -d', kana: 'docker compose up -d', flavor: '再起動' },
    ],
  },
  {
    name: 'SSH接続不可',
    description: '本番サーバーにSSH接続ができなくなりました',
    commands: [
      { word: 'ssh -v production', kana: 'ssh -v production', flavor: '接続デバッグ' },
      { word: 'ping production-server', kana: 'ping production-server', flavor: '疎通確認' },
      { word: 'systemctl restart sshd', kana: 'systemctl restart sshd', flavor: 'SSH再起動（コンソールから）' },
    ],
  },
]

export const INCIDENT_MULTIPLIER_MIN = 5.0
export const INCIDENT_MULTIPLIER_MAX = 10.0

// ── 各モード共通スーパーボーナス突入確率（ワード完了ごと）──
// 通常ボーナスはrm -rf /*(1/34≒3%)で判定、障害対応・ガチャはこの確率で判定
export const SUPER_BONUS_PER_WORD_CHANCE = 0.03

// ── 案件ガチャモード ──
export const GACHA_RARITY_TABLE: { rarity: import('../types/game.ts').GachaRarity; weight: number }[] = [
  { rarity: 'SSR', weight: 5 },
  { rarity: 'SR', weight: 15 },
  { rarity: 'R', weight: 40 },
  { rarity: 'N', weight: 40 },
]

export const GACHA_MULTIPLIERS: Record<Exclude<import('../types/game.ts').GachaRarity, 'UR'>, number> = {
  SSR: 12.0,
  SR: 8.0,
  R: 6.0,
  N: 4.0,
}

export const GACHA_PROJECTS: Record<Exclude<import('../types/game.ts').GachaRarity, 'UR'>, { name: string; words: import('../types/game.ts').Word[] }[]> = {
  SSR: [
    { name: 'フルリモート自社開発', words: [
      { word: 'ls', kana: 'ls', flavor: '最高の案件を引いた' },
      { word: 'pwd', kana: 'pwd', flavor: '在宅勤務の幸せ' },
      { word: 'cd ~', kana: 'cd ~', flavor: '家が職場' },
    ]},
    { name: '定時帰りホワイト企業', words: [
      { word: 'exit', kana: 'exit', flavor: '17時30分退勤' },
      { word: 'logout', kana: 'logout', flavor: 'お先に失礼します' },
      { word: 'bye', kana: 'bye', flavor: 'さようなら' },
    ]},
    { name: '高単価フリーランス案件', words: [
      { word: 'echo "hello"', kana: 'echo "hello"', flavor: '月単価100万超え' },
      { word: 'date', kana: 'date', flavor: '稼働日数も自由' },
      { word: 'whoami', kana: 'whoami', flavor: '自分の名前で仕事する' },
    ]},
    { name: '自社サービス開発', words: [
      { word: 'git init', kana: 'git init', flavor: 'ゼロから作る喜び' },
      { word: 'npm create', kana: 'npm create', flavor: '技術選定も自分で' },
      { word: 'open localhost', kana: 'open localhost', flavor: '自分のプロダクト' },
    ]},
  ],
  SR: [
    { name: 'モダン技術スタック案件', words: [
      { word: 'git pull origin main', kana: 'git pull origin main', flavor: 'TypeScript + React' },
      { word: 'npm run build', kana: 'npm run build', flavor: 'CI/CDも完備' },
      { word: 'docker compose up', kana: 'docker compose up', flavor: 'コンテナ環境' },
    ]},
    { name: 'スタートアップ案件', words: [
      { word: 'yarn dev', kana: 'yarn dev', flavor: 'スピード重視' },
      { word: 'vercel deploy', kana: 'vercel deploy', flavor: 'モダンなインフラ' },
      { word: 'prisma migrate', kana: 'prisma migrate', flavor: '最新ORM' },
    ]},
    { name: 'AWS案件', words: [
      { word: 'aws s3 sync . s3://bucket', kana: 'aws s3 sync . s3://bucket', flavor: 'クラウドネイティブ' },
      { word: 'terraform plan', kana: 'terraform plan', flavor: 'IaC完備' },
      { word: 'kubectl get pods', kana: 'kubectl get pods', flavor: 'K8s運用' },
    ]},
    { name: 'データ分析案件', words: [
      { word: 'jupyter notebook', kana: 'jupyter notebook', flavor: 'Pythonで分析' },
      { word: 'pip install pandas', kana: 'pip install pandas', flavor: 'データ処理の定番' },
      { word: 'python train.py', kana: 'python train.py', flavor: '機械学習もやる' },
    ]},
  ],
  R: [
    { name: 'Java保守案件', words: [
      { word: 'mvn clean install', kana: 'mvn clean install', flavor: 'ビルドに5分かかる' },
      { word: 'tail -f catalina.out', kana: 'tail -f catalina.out', flavor: 'Tomcatログ監視' },
      { word: 'vi applicationContext.xml', kana: 'vi applicationContext.xml', flavor: 'XML地獄' },
    ]},
    { name: 'インフラ監視案件', words: [
      { word: 'ssh production-server', kana: 'ssh production-server', flavor: 'いつもの本番接続' },
      { word: 'top -c', kana: 'top -c', flavor: 'リソース監視' },
      { word: 'zabbix_sender -s host', kana: 'zabbix_sender -s host', flavor: '監視データ送信' },
    ]},
    { name: 'PHP案件', words: [
      { word: 'php artisan migrate', kana: 'php artisan migrate', flavor: 'Laravelの世界' },
      { word: 'composer install', kana: 'composer install', flavor: '依存関係インストール' },
      { word: 'php -S localhost:8000', kana: 'php -S localhost:8000', flavor: 'ビルトインサーバー' },
    ]},
    { name: 'ネットワーク保守案件', words: [
      { word: 'traceroute 8.8.8.8', kana: 'traceroute 8.8.8.8', flavor: '経路調査' },
      { word: 'tcpdump -i eth0', kana: 'tcpdump -i eth0', flavor: 'パケットキャプチャ' },
      { word: 'nslookup example.com', kana: 'nslookup example.com', flavor: 'DNS引いてみる' },
    ]},
  ],
  N: [
    { name: 'レガシーVBA案件', words: [
      { word: 'cscript //nologo legacy.vbs', kana: 'cscript //nologo legacy.vbs', flavor: 'VBScript実行' },
      { word: 'reg query HKLM /s /f value', kana: 'reg query HKLM /s /f value', flavor: 'レジストリ調査' },
      { word: 'schtasks /create /tn backup', kana: 'schtasks /create /tn backup', flavor: 'タスクスケジューラ' },
    ]},
    { name: 'エクセル方眼紙案件', words: [
      { word: 'copy /b sheet1.xlsx+sheet2.xlsx merged.xlsx', kana: 'copy /b sheet1.xlsx+sheet2.xlsx merged.xlsx', flavor: 'エクセル結合の闇' },
      { word: 'wmic process list brief', kana: 'wmic process list brief', flavor: '古のWindowsコマンド' },
      { word: 'net use Z: \\\\server\\share', kana: 'net use Z: \\\\server\\share', flavor: '共有フォルダマッピング' },
    ]},
    { name: 'COBOL移行案件', words: [
      { word: 'cobc -x -o output legacy.cob', kana: 'cobc -x -o output legacy.cob', flavor: '化石言語のコンパイル' },
      { word: 'iconv -f SJIS -t UTF-8 data.dat', kana: 'iconv -f SJIS -t UTF-8 data.dat', flavor: '文字コード変換地獄' },
      { word: 'diff -u old_spec.txt new_spec.txt', kana: 'diff -u old_spec.txt new_spec.txt', flavor: '仕様書の差分1000行' },
    ]},
    { name: 'オンプレ移行案件', words: [
      { word: 'rsync -avz /data/ backup:/data/', kana: 'rsync -avz /data/ backup:/data/', flavor: 'データ移行に3日かかる' },
      { word: 'fdisk -l /dev/sda', kana: 'fdisk -l /dev/sda', flavor: 'パーティション確認' },
      { word: 'mount -t nfs server:/share /mnt', kana: 'mount -t nfs server:/share /mnt', flavor: 'NFS設定' },
    ]},
  ],
}

export const REEL_SYMBOLS = [
  'SES', 'Java', 'Excel', '客先', '単価',
  '炎上', 'NULL', '404', 'Bug', '残業',
] as const

export const FAKE_FILE_PATHS = [
  '/usr/lib/libpthread.so',
  '/etc/passwd',
  '/var/log/syslog',
  '/home/ses-engineer/.bashrc',
  '/opt/tomcat/webapps/ROOT',
  '/usr/bin/python3',
  '/etc/nginx/nginx.conf',
  '/var/www/html/index.php',
  '/home/ses-engineer/.ssh/id_rsa',
  '/usr/local/bin/node',
  '/etc/hosts',
  '/var/lib/mysql/ibdata1',
  '/usr/share/java/commons-lang.jar',
  '/opt/app/config/production.yml',
  '/home/ses-engineer/Documents/スキルシート.xlsx',
  '/tmp/build-cache/node_modules',
  '/var/run/docker.sock',
  '/etc/systemd/system/app.service',
  '/home/ses-engineer/.gitconfig',
  '/usr/lib/jvm/java-11-openjdk',
  '/opt/redis/dump.rdb',
  '/var/log/app/error.log',
  '/etc/crontab',
  '/home/ses-engineer/月次報告書.docx',
  '/usr/local/share/ca-certificates',
  '/opt/app/src/main/java/App.java',
  '/var/backups/daily.tar.gz',
  '/etc/ssl/private/server.key',
  '/home/ses-engineer/.vimrc',
  '/usr/lib/systemd/systemd',
]

/** コンボ数に応じたボーナス突入確率テーブル */
export const BONUS_TRIGGER_TABLE: { min: number; chance: number }[] = [
  { min: 100, chance: 1 / 16 },
  { min: 90,  chance: 1 / 32 },
  { min: 80,  chance: 1 / 64 },
  { min: 70,  chance: 1 / 128 },
  { min: 50,  chance: 1 / 256 },
  { min: 40,  chance: 1 / 512 },
  { min: 30,  chance: 1 / 1024 },
  { min: 20,  chance: 1 / 2048 },
  { min: 10,  chance: 1 / 4096 },
  { min: 0,   chance: 1 / 8192 },
]

// min = 必要月数
export const RANKS: RankInfo[] = [
  { min: 1200, rank: '常駐の概念を超えた者', comment: '100年常駐。もはや伝説を超えた神話' },
  { min: 960, rank: 'SES界の生ける化石', comment: '80年常駐。あなたの常駐歴が歴史の教科書に載る' },
  { min: 720, rank: '常駐の仙人', comment: '60年常駐。悟りを開き、客先と一体化した' },
  { min: 600, rank: '人間国宝級常駐員', comment: '50年常駐。国が保護すべき存在' },
  { min: 480, rank: '常駐界のレジェンド', comment: '40年常駐。入社から定年まで客先にいた男' },
  { min: 360, rank: 'SES皇帝', comment: '30年常駐。客先の社長より社歴が長い' },
  { min: 240, rank: '客先の主', comment: '20年常駐。もう自社の人間に顔を忘れられた' },
  { min: 180, rank: '伝説の常駐員', comment: '15年常駐。客先のビル建て替えを経験' },
  { min: 120, rank: '永久常駐の神', comment: '10年常駐。もはやSES沼の主' },
  { min: 84, rank: 'SESの重鎮', comment: '7年常駐。後輩が2回転職しても自分はここにいる' },
  { min: 60, rank: 'ベテラン常駐員', comment: '5年戦士。現場の生き字引' },
  { min: 36, rank: '中堅エンジニア', comment: '3年目。そろそろ後輩の面倒も見る' },
  { min: 24, rank: '現場に馴染んだ人', comment: '2年経過。もう客先が実家' },
  { min: 12, rank: '契約更新された人', comment: '1年突破。でもまだ油断できない' },
  { min: 0, rank: '試用期間中', comment: 'まずは3ヶ月生き延びよう' },
]
